# Generated by //toolchains:repos.bzl (nd_llvm_toolchain) from
# toolchains/llvm.BUILD.tpl: llvm.org LLVM {version}, a cc_toolchain for
# arm64-apple-macos{min_os} against the pinned macOS SDK at
#   {sdk}
# Links with this release's ld64.lld (toolchains/README.md, "Linking hosted
# programs"): it reads the SDK's .tbd stubs, which the from-source ld64 can't
# without libtapi (P2-12).

load("@rules_cc//cc/private/toolchain:unix_cc_toolchain_config.bzl", "cc_toolchain_config")
load("@rules_cc//cc/toolchains:cc_toolchain.bzl", "cc_toolchain")

package(default_visibility = ["//visibility:public"])

exports_files(glob(["bin/**"]))

filegroup(
    name = "compiler_files",
    srcs = glob([
        "bin/clang",
        "bin/clang++",
        "bin/clang-{major}",
        "lib/clang/**",
        "include/c++/**",
    ]),
)

filegroup(
    name = "linker_files",
    srcs = glob([
        "bin/clang",
        "bin/clang++",
        "bin/clang-{major}",
        "bin/ld64.lld",
        "bin/lld",
        "lib/clang/**",
        "nd/ld64.lld",
    ]),
)

filegroup(
    name = "ar_files",
    srcs = ["bin/llvm-ar", "bin/llvm-libtool-darwin"],
)

filegroup(
    name = "binutils",
    srcs = glob(["bin/llvm-*", "bin/ld64.lld", "bin/lld"]),
)

filegroup(
    name = "all_files",
    srcs = [":compiler_files", ":linker_files", ":ar_files", ":binutils"],
)

filegroup(name = "empty")

# The deployment target comes from --macos_minimum_os (-mmacosx-version-min,
# .bazelrc config:pinned); the triple carries it for Swift.
_TARGET = "arm64-apple-macos{min_os}"

_SDK = "{sdk}"

cc_toolchain_config(
    name = "config",
    abi_libc_version = "darwin_arm64",
    abi_version = "darwin_arm64",
    compiler = "clang",
    cpu = "darwin_arm64",
    host_system_name = "arm64-apple-macos",
    target_libc = "macosx",
    target_system_name = _TARGET,
    toolchain_identifier = "nd-llvm-{version}-darwin-arm64",
    builtin_sysroot = _SDK,
    cxx_builtin_include_directories = [
        "{resource_dir}/include",
        # The whole SDK: clang also records SDKSettings.json as a dependency.
        _SDK,
        "{root}/include/c++/v1",
    ],
    compile_flags = [
        "--target=arm64-apple-macos",
        "-isysroot",
        _SDK,
        "-fcolor-diagnostics",
        "-fno-omit-frame-pointer",
        "-Wall",
        "-U_FORTIFY_SOURCE",
        "-fstack-protector",
    ],
    cxx_flags = ["-std=c++20"],
    dbg_compile_flags = ["-g"],
    opt_compile_flags = [
        "-g0",
        "-O2",
        "-D_FORTIFY_SOURCE=1",
        "-DNDEBUG",
        "-ffunction-sections",
        "-fdata-sections",
    ],
    unfiltered_compile_flags = [
        "-no-canonical-prefixes",
        "-Wno-builtin-macro-redefined",
        "-D__DATE__=\"redacted\"",
        "-D__TIMESTAMP__=\"redacted\"",
        "-D__TIME__=\"redacted\"",
    ],
    link_flags = [
        "--target=arm64-apple-macos",
        "-isysroot",
        _SDK,
        "-fuse-ld=lld",
        "--ld-path=external/{repo}/nd/ld64.lld",
        "-headerpad_max_install_names",
        # rules_cc's macOS features add -fobjc-link-runtime and -lc++; keep
        # only the dylibs a program uses.
        "-Wl,-dead_strip_dylibs",
        # Swift: the OS's runtime, whose stubs are in the SDK.
        "-L" + _SDK + "/usr/lib/swift",
        "-Wl,-rpath,/usr/lib/swift",
    ],
    link_libs = ["-lc++"],
    opt_link_flags = ["-Wl,-dead_strip"],
    coverage_compile_flags = ["-fprofile-instr-generate", "-fcoverage-mapping"],
    coverage_link_flags = ["-fprofile-instr-generate"],
    supports_start_end_lib = False,
    tool_paths = {
        "ar": "bin/llvm-ar",
        "libtool": "bin/llvm-libtool-darwin",
        "cpp": "bin/clang-cpp",
        "dwp": "bin/llvm-dwp",
        "gcc": "bin/clang",
        "gcov": "bin/llvm-cov",
        "ld": "bin/ld64.lld",
        "llvm-cov": "bin/llvm-cov",
        "llvm-profdata": "bin/llvm-profdata",
        "nm": "bin/llvm-nm",
        "objcopy": "bin/llvm-objcopy",
        "objdump": "bin/llvm-objdump",
        "strip": "bin/llvm-strip",
    },
)

cc_toolchain(
    name = "cc",
    all_files = ":all_files",
    ar_files = ":ar_files",
    as_files = ":compiler_files",
    compiler_files = ":compiler_files",
    dwp_files = ":empty",
    linker_files = ":linker_files",
    objcopy_files = ":binutils",
    strip_files = ":binutils",
    supports_param_files = 1,
    toolchain_config = ":config",
    toolchain_identifier = "nd-llvm-{version}-darwin-arm64",
)

toolchain(
    name = "cc_toolchain",
    exec_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
    toolchain = ":cc",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
