# Generated by //toolchains:repos.bzl (nd_swift_toolchain) from
# toolchains/swift.BUILD.tpl: the swift.org {version} toolchain for macOS,
# expanded from its .pkg into {tc}, and a rules_swift toolchain on it for
# arm64-apple-macos. Its -sdk is the pinned cc_toolchain's sysroot, the pinned
# macOS SDK (@nd_macos_sdk). Linking goes through the
# pinned cc_toolchain (@nd_llvm), which adds the Swift runtime's search path
# and rpath (the OS's /usr/lib/swift), so the toolchain itself contributes no
# link flags (os = "none").

load("@rules_swift//swift/toolchains:swift_toolchain.bzl", "swift_toolchain")
load("@rules_swift//swift/toolchains:swift_tools.bzl", "swift_tools")

package(default_visibility = ["//visibility:public"])

exports_files(["swift_version.txt"])

filegroup(
    name = "files",
    srcs = glob(
        [
            "{tc}/usr/bin/swift*",
            "{tc}/usr/bin/clang*",
            "{tc}/usr/lib/swift/**",
            "{tc}/usr/lib/clang/**",
            "{tc}/usr/lib/lib*.dylib",
            "{tc}/usr/lib/swift_static/**",
            "{tc}/usr/lib/host/**",
            "{tc}/usr/include/**",
        ],
        allow_empty = True,
    ),
)

swift_tools(
    name = "tools",
    additional_inputs = [":files"],
    swift_autolink_extract = "{tc}/usr/bin/swift-autolink-extract",
    swift_driver = "{tc}/usr/bin/swiftc",
    swift_symbolgraph_extract = "{tc}/usr/bin/swift-symbolgraph-extract",
)

swift_toolchain(
    name = "swift",
    arch = "arm64",
    os = "none",
    parsed_version = "{version}",
    swift_tools = ":tools",
    version_file = "swift_version.txt",
)

toolchain(
    name = "swift_toolchain",
    exec_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:aarch64",
    ],
    toolchain = ":swift",
    toolchain_type = "@rules_swift//toolchains:toolchain_type",
)
