load("//rules:swift.bzl", "nd_swift_binary", "nd_swift_library")

package(default_visibility = ["//visibility:public"])

nd_swift_library(
    name = "kcheck_lib",
    srcs = ["Check.swift"],
    module_name = "KCheck",
    deps = ["//tools/macho:MachO"],
)

nd_swift_binary(
    name = "kcheck",
    srcs = ["main.swift"],
    deps = [":kcheck_lib"],
)

exports_files(["kcheck_test.sh"])
