"""XNU build rules, phase 1: the upstream makefiles run inside Bazel actions.

docs/architecture/build-system.md §4. Phase 2 replaces the makefiles with a
native graph generated by tools/xnu2bazel; these rules keep the same targets.

Phase-1 hermeticity limits, stated rather than hidden: the base macOS SDK and
the compiler come from the host's selected Xcode (toolchains/README.md), and
actions need the Xcode installation, so they run locally on macOS.
"""

_XCODE_REQS = {"requires-darwin": "", "no-remote": ""}

def _scripts(ctx):
    return ctx.files._scripts

def _path_of(files, marker):
    """Directory of an external repository, from any file in it."""
    for f in files:
        i = f.path.find(marker)
        if i >= 0:
            return f.path[:i + len(marker)]
    fail("no file under " + marker)

def _repo_root(files):
    f = files[0]
    parts = f.path.split("/")
    return "/".join(parts[:2]) if parts[0] == "external" else f.owner.workspace_root

# ---------------------------------------------------------------------------

def _nd_build_sdk_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name)
    shim_root = ctx.attr.shim_root
    ctx.actions.run(
        executable = ctx.file._mksdk,
        arguments = [
            out.path,
            _repo_root(ctx.files.availability_versions),
            _repo_root(ctx.files.libdispatch),
            ctx.label.package + "/" + shim_root,
        ],
        inputs = ctx.files.availability_versions + ctx.files.libdispatch + ctx.files.shims + _scripts(ctx),
        outputs = [out],
        mnemonic = "NDBuildSDK",
        progress_message = "Assembling NeoDarwin build SDK %{label}",
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset([out]))]

nd_build_sdk = rule(
    implementation = _nd_build_sdk_impl,
    doc = "The NeoDarwin additions to the host macOS SDK: Apple open-source build tools and NeoDarwin shims (real files only).",
    attrs = {
        "availability_versions": attr.label(mandatory = True, allow_files = True),
        "libdispatch": attr.label(mandatory = True, allow_files = True),
        "shims": attr.label(mandatory = True, allow_files = True),
        "shim_root": attr.string(mandatory = True, doc = "Package-relative directory the shims are rooted at."),
        "_mksdk": attr.label(default = "//tools/xnu:mksdk.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
    },
)

# ---------------------------------------------------------------------------

def _xnu_headers_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name)
    sdk = ctx.file.sdk
    ctx.actions.run(
        executable = ctx.file._script,
        arguments = [out.path, _repo_root(ctx.files.srcs), sdk.path, ctx.attr.darwin_version],
        inputs = ctx.files.srcs + [sdk] + _scripts(ctx),
        outputs = [out],
        mnemonic = "XnuHeaders",
        progress_message = "Installing XNU headers %{label}",
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset([out]))]

xnu_headers = rule(
    implementation = _xnu_headers_impl,
    doc = "make installhdrs: Kernel.framework and usr/local headers from XNU.",
    attrs = {
        "srcs": attr.label(mandatory = True, allow_files = True),
        "sdk": attr.label(mandatory = True, allow_single_file = True),
        "darwin_version": attr.string(mandatory = True),
        "_script": attr.label(default = "//tools/xnu:headers.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
    },
)

# ---------------------------------------------------------------------------

def _libfirehose_kernel_impl(ctx):
    out = ctx.actions.declare_file("lib%s.a" % ctx.label.name)
    ctx.actions.run(
        executable = ctx.file._script,
        arguments = [out.path, _repo_root(ctx.files.libdispatch), ctx.file.headers.path, ctx.file.sdk.path, ctx.attr.arch],
        inputs = ctx.files.libdispatch + [ctx.file.headers, ctx.file.sdk] + _scripts(ctx),
        outputs = [out],
        mnemonic = "Firehose",
        progress_message = "Building libfirehose_kernel %{label}",
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset([out]))]

libfirehose_kernel = rule(
    implementation = _libfirehose_kernel_impl,
    doc = "libfirehose_kernel.a from libdispatch's src/firehose/firehose_buffer.c.",
    attrs = {
        "libdispatch": attr.label(mandatory = True, allow_files = True),
        "headers": attr.label(mandatory = True, allow_single_file = True),
        "sdk": attr.label(mandatory = True, allow_single_file = True),
        "arch": attr.string(default = "arm64e"),
        "_script": attr.label(default = "//tools/xnu:firehose.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
    },
)

# ---------------------------------------------------------------------------

def _xnu_kernel_impl(ctx):
    report = ctx.actions.declare_file(ctx.label.name + ".report.txt")
    outputs = [report]
    kernel_arg = "-"
    if not ctx.attr.link_gap_report:
        kernel = ctx.actions.declare_file("kernel.%s.%s" % (ctx.attr.kernel_config.lower(), ctx.attr.machine_config.lower()))
        outputs.append(kernel)
        kernel_arg = kernel.path
    args = [
        report.path,
        kernel_arg,
        _repo_root(ctx.files.srcs),
        ctx.file.sdk.path,
        ctx.file.firehose.path,
        ctx.attr.darwin_version,
        ctx.attr.arch_config,
        ctx.attr.machine_config,
        ctx.attr.kernel_config,
    ] + [p.path for p in ctx.files.patches]
    ctx.actions.run(
        executable = ctx.file._script,
        arguments = args,
        inputs = ctx.files.srcs + ctx.files.patches + [ctx.file.sdk, ctx.file.firehose] + _scripts(ctx),
        outputs = outputs,
        mnemonic = "XnuKernel",
        progress_message = "Building XNU %s %s %s %%{label}" % (ctx.attr.arch_config, ctx.attr.machine_config, ctx.attr.kernel_config),
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset(outputs))]

xnu_kernel = rule(
    implementation = _xnu_kernel_impl,
    doc = """Build an XNU kernel with the upstream makefiles.

    With link_gap_report = True the product is the report alone: the action
    succeeds when every source compiles and the link fails only on undefined
    symbols, which the report lists. That is how the kernel's remaining
    dependency on Apple's closed archives is measured and burned down.
    """,
    attrs = {
        "srcs": attr.label(mandatory = True, allow_files = True),
        "sdk": attr.label(mandatory = True, allow_single_file = True),
        "firehose": attr.label(mandatory = True, allow_single_file = True),
        "patches": attr.label_list(allow_files = [".patch"]),
        "darwin_version": attr.string(mandatory = True),
        "arch_config": attr.string(default = "ARM64"),
        "machine_config": attr.string(mandatory = True),
        "kernel_config": attr.string(default = "RELEASE"),
        "link_gap_report": attr.bool(default = False),
        "_script": attr.label(default = "//tools/xnu:kernel.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
    },
)
