"""XNU build rules, phase 1: the upstream makefiles run inside Bazel actions.

docs/architecture/build-system.md §4. Phase 2 replaces the makefiles with a
native graph generated by tools/xnu2bazel; these rules keep the same targets.

Phase-1 hermeticity limits, stated rather than hidden: the base macOS SDK and
the compiler come from the host's selected Xcode (toolchains/README.md), and
actions need the Xcode installation, so they run locally on macOS.
"""

load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")

_XCODE_REQS = {"requires-darwin": "", "no-remote": ""}

def _scripts(ctx):
    return ctx.files._scripts

def _path_of(files, marker):
    """Directory of an external repository, from any file in it."""
    for f in files:
        i = f.path.find(marker)
        if i >= 0:
            return f.path[:i + len(marker)]
    fail("no file under " + marker)

def _repo_root(files):
    f = files[0]
    parts = f.path.split("/")
    return "/".join(parts[:2]) if parts[0] == "external" else f.owner.workspace_root

# ---------------------------------------------------------------------------

def _nd_build_sdk_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name)
    shim_root = ctx.attr.shim_root
    ctx.actions.run(
        executable = ctx.file._mksdk,
        arguments = [
            out.path,
            _repo_root(ctx.files.availability_versions),
            _repo_root(ctx.files.libdispatch),
            ctx.label.package + "/" + shim_root,
        ],
        inputs = ctx.files.availability_versions + ctx.files.libdispatch + ctx.files.shims + _scripts(ctx),
        outputs = [out],
        mnemonic = "NDBuildSDK",
        progress_message = "Assembling NeoDarwin build SDK %{label}",
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset([out]))]

nd_build_sdk = rule(
    implementation = _nd_build_sdk_impl,
    doc = "The NeoDarwin additions to the host macOS SDK: Apple open-source build tools and NeoDarwin shims (real files only).",
    attrs = {
        "availability_versions": attr.label(mandatory = True, allow_files = True),
        "libdispatch": attr.label(mandatory = True, allow_files = True),
        "shims": attr.label(mandatory = True, allow_files = True),
        "shim_root": attr.string(mandatory = True, doc = "Package-relative directory the shims are rooted at."),
        "_mksdk": attr.label(default = "//tools/xnu:mksdk.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
    },
)

# ---------------------------------------------------------------------------

def _xnu_headers_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name)
    sdk = ctx.file.sdk
    ctx.actions.run(
        executable = ctx.file._script,
        arguments = [out.path, _repo_root(ctx.files.srcs), sdk.path, ctx.attr.darwin_version],
        inputs = ctx.files.srcs + [sdk] + _scripts(ctx),
        outputs = [out],
        mnemonic = "XnuHeaders",
        progress_message = "Installing XNU headers %{label}",
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset([out]))]

xnu_headers = rule(
    implementation = _xnu_headers_impl,
    doc = "make installhdrs: Kernel.framework and usr/local headers from XNU.",
    attrs = {
        "srcs": attr.label(mandatory = True, allow_files = True),
        "sdk": attr.label(mandatory = True, allow_single_file = True),
        "darwin_version": attr.string(mandatory = True),
        "_script": attr.label(default = "//tools/xnu:headers.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
    },
)

# ---------------------------------------------------------------------------

def _libfirehose_kernel_impl(ctx):
    out = ctx.actions.declare_file("lib%s.a" % ctx.label.name)
    ctx.actions.run(
        executable = ctx.file._script,
        arguments = [out.path, _repo_root(ctx.files.libdispatch), ctx.file.headers.path, ctx.file.sdk.path, ctx.attr.arch],
        inputs = ctx.files.libdispatch + [ctx.file.headers, ctx.file.sdk] + _scripts(ctx),
        outputs = [out],
        mnemonic = "Firehose",
        progress_message = "Building libfirehose_kernel %{label}",
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset([out]))]

libfirehose_kernel = rule(
    implementation = _libfirehose_kernel_impl,
    doc = "libfirehose_kernel.a from libdispatch's src/firehose/firehose_buffer.c.",
    attrs = {
        "libdispatch": attr.label(mandatory = True, allow_files = True),
        "headers": attr.label(mandatory = True, allow_single_file = True),
        "sdk": attr.label(mandatory = True, allow_single_file = True),
        "arch": attr.string(default = "arm64e"),
        "_script": attr.label(default = "//tools/xnu:firehose.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
    },
)

# ---------------------------------------------------------------------------

def _xnu_kernel_impl(ctx):
    report = ctx.actions.declare_file(ctx.label.name + ".report.txt")
    outputs = [report]
    kernel_arg = "-"
    if not ctx.attr.link_gap_report:
        kernel = ctx.actions.declare_file("kernel.%s.%s" % (ctx.attr.kernel_config.lower(), ctx.attr.machine_config.lower()))
        unstripped = ctx.actions.declare_file(kernel.basename + ".unstripped", sibling = kernel)
        outputs += [kernel, unstripped]
        kernel_arg = kernel.path
    # Overlay manifest: "destination<TAB>source" per file, the destination
    # being the overlay directory plus the file's path in its own package.
    overlay_files = []
    lines = []
    for target, dest in ctx.attr.overlays.items():
        for f in target.files.to_list():
            overlay_files.append(f)
            lines.append("%s/%s\t%s" % (dest, f.owner.name, f.path))
    make_vars = list(ctx.attr.make_vars)
    linker = ctx.attr._kernel_linker[BuildSettingInfo].value
    if linker == "lld":
        # --//rules:kernel_linker=lld: XNU's LD is clang++ -nostdlib; clang
        # runs tools/xnu/ld64_lld.sh (copied into the tree) as its linker.
        wrapper = ctx.file._ld64_lld_wrapper
        overlay_files.append(wrapper)
        lines.append("tools/nd/%s\t%s" % (wrapper.basename, wrapper.path))
        make_vars += [
            "LD=$(KC++) --ld-path=$(SRCROOT)/tools/nd/%s -nostdlib" % wrapper.basename,
            "ND_LD64_LLD=" + ctx.attr._ld64_lld[BuildSettingInfo].value,
        ]
    elif linker == "ld64":
        # --//rules:kernel_linker=ld64: XNU's LD is clang++ -nostdlib with
        # the from-source ld64 (copied into the tree) as its linker.
        ld = ctx.executable._ld64
        overlay_files.append(ld)
        lines.append("tools/nd/ld64/ld\t%s" % ld.path)
        make_vars.append("LD=$(KC++) --ld-path=$(SRCROOT)/tools/nd/ld64/ld -nostdlib")
    overlay_arg = "-"
    if lines:
        manifest = ctx.actions.declare_file(ctx.label.name + ".overlay")
        ctx.actions.write(manifest, "\n".join(sorted(lines)) + "\n")
        overlay_files.append(manifest)
        overlay_arg = manifest.path
    args = [
        report.path,
        kernel_arg,
        _repo_root(ctx.files.srcs),
        ctx.file.sdk.path,
        ctx.file.firehose.path,
        ctx.attr.darwin_version,
        ctx.attr.arch_config,
        ctx.attr.machine_config,
        ctx.attr.kernel_config,
        overlay_arg,
    ] + [p.path for p in ctx.files.patches] + ["--"] + make_vars
    ctx.actions.run(
        executable = ctx.file._script,
        arguments = args,
        inputs = ctx.files.srcs + ctx.files.patches + overlay_files + [ctx.file.sdk, ctx.file.firehose] + _scripts(ctx),
        outputs = outputs,
        mnemonic = "XnuKernel",
        progress_message = "Building XNU %s %s %s %%{label}" % (ctx.attr.arch_config, ctx.attr.machine_config, ctx.attr.kernel_config),
        execution_requirements = _XCODE_REQS,
        use_default_shell_env = True,
    )
    return [DefaultInfo(files = depset(outputs))]

xnu_kernel = rule(
    implementation = _xnu_kernel_impl,
    doc = """Build an XNU kernel with the upstream makefiles.

    With link_gap_report = True the product is the report alone: the action
    succeeds when every source compiles and the link fails only on undefined
    symbols, which the report lists. That is how the kernel's remaining
    dependency on Apple's closed archives is measured and burned down.
    """,
    attrs = {
        "srcs": attr.label(mandatory = True, allow_files = True),
        "sdk": attr.label(mandatory = True, allow_single_file = True),
        "firehose": attr.label(mandatory = True, allow_single_file = True),
        "patches": attr.label_list(allow_files = [".patch"]),
        "overlays": attr.label_keyed_string_dict(
            allow_files = True,
            doc = "Files to add to the source tree before patching: {files: directory in the xnu tree}. Each file keeps its path within its own package. NeoDarwin-owned sources enter the kernel this way; patches then add them to the build lists.",
        ),
        "darwin_version": attr.string(mandatory = True),
        "arch_config": attr.string(default = "ARM64"),
        "machine_config": attr.string(mandatory = True),
        "kernel_config": attr.string(default = "RELEASE"),
        "link_gap_report": attr.bool(default = False),
        "make_vars": attr.string_list(doc = "Extra VAR=value arguments for make, e.g. ARCH_STRING_FOR_CURRENT_MACHINE_CONFIG=arm64."),
        "_script": attr.label(default = "//tools/xnu:kernel.sh", allow_single_file = True),
        "_scripts": attr.label(default = "//tools/xnu:scripts"),
        "_kernel_linker": attr.label(default = "//rules:kernel_linker"),
        "_ld64_lld": attr.label(default = "//rules:ld64_lld"),
        "_ld64_lld_wrapper": attr.label(default = "//tools/xnu:ld64_lld.sh", allow_single_file = True),
        "_ld64": attr.label(default = "//toolchains/ld64", executable = True, cfg = "exec"),
    },
)
